name: Adhoc tests
on:
  workflow_dispatch:
    inputs:
      path:
        description: "Path of the notebook/script to test, relative to the repo root. For scripts, this should be the path of the `scripts` folder"
        required: true
        type: string
      python_version:
        description: "Python version"
        required: true
        default: "3.10"
        type: choice
        options:
            - "3.8"
            - "3.9"
            - "3.10"
            - "3.11"
      os:
        description: "Windows/Linux/MacOS"
        required: true
        default: "linux-latest"
        type: choice
        options:
            - linux-latest
            - macos-latest
            - windows-latest
jobs:
  test-notebooks:
    if: contains(${{ inputs.path }}, '.ipynb')
    runs-on: ${{ inputs.os }}
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
            python-version: ${{ inputs.python_version }}
            cache: "pip"
        - name: Install OpenMP on MacOS for XGBoost integration
          if: runner.os == 'macOS'
          run: brew install libomp
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Test examples
          uses: nick-fields/retry@v2
          env:
            NEPTUNE_API_TOKEN: "ANONYMOUS"
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
          with:
            timeout_minutes: 60
            max_attempts: 2
            retry_on: timeout
            command: ipython ${{ inputs.path }}
  test-scripts:
      if: contains(${{ inputs.path }}, '/scripts')
      runs-on: ${{ inputs.os }}
      steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-python@v4
            with:
              python-version: ${{ inputs.python_version }}
              cache: "pip"
          - name: Install OpenMP on MacOS for XGBoost integration
            if: runner.os == 'macOS'
            run: brew install libomp
          - name: Test examples
            uses: nick-fields/retry@v2
            env:
                NEPTUNE_API_TOKEN: "ANONYMOUS"
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
            with:
                timeout_minutes: 60
                max_attempts: 2
                retry_on: timeout
                command: |
                    cd ${{ inputs.path }}
                    bash run_examples.sh
